parser = { __? ~ (number | string) ~ __? }

// 除外
SPACE = _{ " " }
__ = _{ SPACE* }

// 変数
// ident = { (('a'..'z') | ('A'..'Z') | ("_") | ('0'..'9'))* }
// variable_declaration = ident _ (":" / "=") _ expression

// 数字型
number = { float | integer }
float = { integer ~ "." ~ digit+ }
integer = { "0" | "-"? ~ non_zero_digit ~ digit* }
non_zero_digit = { '1'..'9' }
digit = { '0'..'9' }

// 文字列型
string = { "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
